import type { Response } from 'express';
import { access, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type {
	CallbackWaitRegistration,
	FromAIArgument,
	IDataObject,
	IExecuteFunctions,
	INode,
	IWebhookDescription,
	IWebhookFunctions,
	IWorkflowSettings,
} from 'n8n-workflow';
import {
	getNodeWebhookPath,
	getToolDescriptionForNode,
	NodeOperationError,
	resolveWebhookDescriptionField,
	traverseNodeParameters,
	WAIT_INDEFINITELY,
	webhookDescriptionIsNativelyResolvable,
} from 'n8n-workflow';
import { WebhookAuthorizationError } from 'n8n-nodes-base/dist/nodes/Webhook/error';
import { validateWebhookAuthentication } from 'n8n-nodes-base/dist/nodes/Webhook/utils';
import { mock } from 'vitest-mock-extended';

import { ToolWaitForCallback } from '../ToolWaitForCallback.node';
import { toolDescriptionProperty } from '../descriptions';

// The credential check itself is the Webhook node's, tested there. What is the tool's own is
// what it does with the outcome, so only that one helper is replaced.
vi.mock('n8n-nodes-base/dist/nodes/Webhook/utils', async (importOriginal) => ({
	...(await importOriginal<typeof import('n8n-nodes-base/dist/nodes/Webhook/utils')>()),
	validateWebhookAuthentication: vi.fn(),
}));

const NODE = mock<INode>({
	id: 'node-1',
	name: 'Wait for Callback',
	type: '@n8n/n8n-nodes-langchain.toolWaitForCallback',
	typeVersion: 1,
	webhookId: 'endpoint-a',
	parameters: {},
});

function makeExecuteContext({
	waitIdentifier = '125',
	toolCallId = 'call-1',
	workflowSettings = { executionOrder: 'v1' },
	registerCallbackWait = vi.fn(),
}: {
	waitIdentifier?: unknown;
	toolCallId?: string;
	workflowSettings?: IWorkflowSettings;
	registerCallbackWait?: ReturnType<typeof vi.fn>;
} = {}) {
	return mock<IExecuteFunctions>({
		getNode: () => NODE,
		getExecutionId: () => 'exec-1',
		getWorkflow: () => ({ id: 'wf-1' }) as never,
		getWorkflowSettings: () => workflowSettings,
		getInputData: () => [{ json: { toolCallId, query: 'anything' } }],
		getNodeParameter: ((name: string) =>
			name === 'waitIdentifier' ? waitIdentifier : undefined) as never,
		putExecutionToWait: vi.fn(),
		helpers: { registerCallbackWait } as never,
	});
}

describe('ToolWaitForCallback', () => {
	const node = new ToolWaitForCallback();

	// The tool schema the LLM sees is generated by scanning node parameters for `$fromAI`
	// calls, so "only model-defined parameters are published" is a property of the
	// parameters themselves rather than of any code in this node.
	describe('tool schema', () => {
		const publishedKeys = (parameters: INode['parameters']) => {
			const collected: FromAIArgument[] = [];
			traverseNodeParameters(parameters, collected);
			return collected.map((argument) => argument.key);
		};

		it('publishes the wait identifier when its source is the model', () => {
			expect(
				publishedKeys({
					toolDescription: 'wait for a job',
					waitIdentifier: "={{ $fromAI('waitIdentifier', 'The job id', 'string') }}",
					callbackIdentifier: '={{ $json.body.id }}',
					callbackAuthentication: 'none',
				}),
			).toEqual(['waitIdentifier']);
		});

		it.each([
			['fixed', 'processo-principal'],
			['an expression', '={{ $json.id }}'],
		])('publishes nothing when the wait identifier is %s', (_source, waitIdentifier) => {
			expect(
				publishedKeys({
					waitIdentifier,
					callbackIdentifier: '={{ $json.body.id }}',
				}),
			).toEqual([]);
		});

		it("never publishes the callback identifier, which is the tool's own configuration", () => {
			expect(
				publishedKeys({
					waitIdentifier: "={{ $fromAI('waitIdentifier', 'The job id', 'string') }}",
					callbackIdentifier: '={{ $json.headers["x-request-id"] }}',
				}),
			).not.toContain('callbackIdentifier');
		});
	});

	// Tool calls of one turn run one after another in the order the model listed them, and this
	// call suspends the run in place. The model can only learn that from the description, so
	// both texts the runtime can hand it carry that clause.
	describe('tool description', () => {
		const withToolDescription = (toolDescription: string) =>
			({ ...NODE, parameters: { toolDescription } }) as INode;

		it('tells the model that later calls of the same turn wait for the callback, by default', () => {
			const description = getToolDescriptionForNode(
				withToolDescription(toolDescriptionProperty.default as string),
				node,
			);

			expect(description).toMatch(/calls listed before this one run first/);
			expect(description).toMatch(/calls listed after it run only once the callback has arrived/);
		});

		it('keeps that clause when the tool description is left empty', () => {
			const description = getToolDescriptionForNode(withToolDescription(''), node);

			expect(description).toMatch(/run only once the callback has arrived/);
		});
	});

	describe('execute', () => {
		it('parks the execution when the wait is registered', async () => {
			const registerCallbackWait = vi.fn().mockResolvedValue({ status: 'registered' });
			const ctx = makeExecuteContext({ registerCallbackWait });

			await node.execute.call(ctx);

			expect(registerCallbackWait).toHaveBeenCalledWith({
				namespace: 'endpoint-a',
				correlationValue: '125',
				executionId: 'exec-1',
				toolCallId: 'call-1',
				nodeId: 'node-1',
				workflowId: 'wf-1',
			} satisfies CallbackWaitRegistration);
			expect(ctx.putExecutionToWait).toHaveBeenCalledWith(WAIT_INDEFINITELY);
		});

		it('records what it is parked on, so a waiting execution is inspectable', async () => {
			const ctx = makeExecuteContext({
				registerCallbackWait: vi.fn().mockResolvedValue({ status: 'registered' }),
			});

			// The engine discards this task on resume, so it never reaches the model — it is
			// what an operator sees when opening the waiting (or cancelled) execution.
			expect(await node.execute.call(ctx)).toEqual([
				[{ json: { status: 'waitingForCallback', waitIdentifier: '125' } }],
			]);
		});

		it('does not echo the model-supplied tool arguments while parked', async () => {
			const ctx = makeExecuteContext({
				registerCallbackWait: vi.fn().mockResolvedValue({ status: 'registered' }),
			});

			const [items] = await node.execute.call(ctx);

			expect(items[0].json).not.toHaveProperty('toolCallId');
		});

		it('tells the canvas what the parked node is waiting for', () => {
			expect(node.description.waitingNodeTooltip).toContain('Callback Identifier');
		});

		it('returns the parked callback body without parking, when one already arrived', async () => {
			const ctx = makeExecuteContext({
				registerCallbackWait: vi
					.fn()
					.mockResolvedValue({ status: 'resolved', payload: { id: 125, status: 'DONE' } }),
			});

			const result = await node.execute.call(ctx);

			expect(result).toEqual([[{ json: { id: 125, status: 'DONE' } }]]);
			expect(ctx.putExecutionToWait).not.toHaveBeenCalled();
		});

		it('normalises a numeric identifier to its string form', async () => {
			const registerCallbackWait = vi.fn().mockResolvedValue({ status: 'registered' });

			await node.execute.call(makeExecuteContext({ waitIdentifier: 125, registerCallbackWait }));

			expect(registerCallbackWait).toHaveBeenCalledWith(
				expect.objectContaining({ correlationValue: '125' }),
			);
		});

		it.each([
			['an empty string', ''],
			['whitespace only', '   '],
			['null', null],
			['an object', { nested: true }],
			['a value beyond the stored length', 'x'.repeat(256)],
		])('refuses an identifier that cannot be correlated: %s', async (_case, waitIdentifier) => {
			const registerCallbackWait = vi.fn();

			await expect(
				node.execute.call(makeExecuteContext({ waitIdentifier, registerCallbackWait })),
			).rejects.toThrow(NodeOperationError);
			expect(registerCallbackWait).not.toHaveBeenCalled();
		});

		it('surfaces a refused registration to the agent', async () => {
			const ctx = makeExecuteContext({
				registerCallbackWait: vi.fn().mockRejectedValue(new Error('already active')),
			});

			await expect(node.execute.call(ctx)).rejects.toThrow('already active');
			expect(ctx.putExecutionToWait).not.toHaveBeenCalled();
		});

		it.each<[string, IWorkflowSettings]>([
			['the legacy order', { executionOrder: 'v0' }],
			['no order set, which the engine treats as legacy', {}],
		])('refuses to run under %s', async (_case, workflowSettings) => {
			const registerCallbackWait = vi.fn();
			const ctx = makeExecuteContext({ workflowSettings, registerCallbackWait });

			// A batch under the legacy order resumes the agent before its tools ran, so a wait
			// registered there could never hand its result back: refuse before registering.
			await expect(node.execute.call(ctx)).rejects.toThrow('v1 (recommended)');
			expect(registerCallbackWait).not.toHaveBeenCalled();
			expect(ctx.putExecutionToWait).not.toHaveBeenCalled();
		});

		it('refuses to park when the runtime grants no way to register a wait', async () => {
			// This is also what an agent that calls its tools in-process looks like: the
			// helper is only granted on the engine's node-execution path. The mock proxies a
			// nested object, so the helper is removed explicitly rather than left out.
			const ctx = makeExecuteContext();
			(ctx as { helpers: unknown }).helpers = { registerCallbackWait: undefined };

			await expect(node.execute.call(ctx)).rejects.toThrow('cannot register a callback wait');
			expect(ctx.putExecutionToWait).not.toHaveBeenCalled();
		});
	});

	describe('callback endpoint', () => {
		const callbackWebhook = node.description.webhooks?.[0] as IWebhookDescription;

		/** The endpoint the backend registers for a node whose `path` parameter holds this. */
		function endpointOf(path: string) {
			const resolution = resolveWebhookDescriptionField(
				{ parameters: { path } },
				callbackWebhook,
				'path',
			);
			if (!resolution.resolved) throw new Error('The path is not read from the node parameters');

			return getNodeWebhookPath('wf-1', NODE, String(resolution.value ?? ''), true);
		}

		it('reads the path from the node parameters, like the Webhook node', () => {
			expect(endpointOf('order-status')).toBe('order-status');
		});

		it('keeps the generated endpoint when no path is given', () => {
			expect(endpointOf('')).toBe('endpoint-a');
		});

		it('resolves every field without the expression engine', () => {
			expect(webhookDescriptionIsNativelyResolvable(callbackWebhook)).toBe(true);
		});

		it('answers on receipt, the only mode an endpoint that starts no run can have', () => {
			const responseMode = resolveWebhookDescriptionField(
				{ parameters: {} },
				callbackWebhook,
				'responseMode',
			);

			expect(responseMode).toEqual({ resolved: true, value: 'onReceived' });
		});
	});

	describe('webhook', () => {
		const makeWebhookContext = ({
			options = {},
			body = {},
			userAgent = 'curl/8.4.0',
			ip = '203.0.113.10',
			contentType = 'application/json',
			evaluateExpression = vi.fn(),
		}: {
			options?: IDataObject;
			body?: unknown;
			userAgent?: string;
			ip?: string;
			contentType?: string;
			evaluateExpression?: ReturnType<typeof vi.fn>;
		} = {}) => {
			const response = mock<Response>({ writeHead: vi.fn(), end: vi.fn() });
			const getBodyData = vi.fn(() => body);

			// `Only Run If` is read off the raw parameters, so the node itself must carry them.
			const node = { ...NODE, parameters: { options } } as INode;

			const ctx = mock<IWebhookFunctions>({
				getNode: () => node,
				getNodeParameter: ((name: string) => (name === 'options' ? options : 'none')) as never,
				getBodyData: getBodyData as never,
				getHeaderData: () => ({}),
				getQueryData: () => ({ trace: 'abc' }),
				getRequestObject: () =>
					({ ip, ips: [], contentType, headers: { 'user-agent': userAgent } }) as never,
				getResponseObject: () => response as never,
				evaluateExpression: evaluateExpression as never,
				logger: mock(),
			});

			return { ctx, response, getBodyData };
		};

		it('returns the callback body and nothing else', async () => {
			const { ctx } = makeWebhookContext({ body: { id: 125, status: 'DONE' } });

			const result = await node.webhook.call(ctx);

			expect(result.workflowData).toEqual([[{ json: { id: 125, status: 'DONE' } }]]);
		});

		it('wraps a non-object body so the tool result stays an object', async () => {
			const { ctx } = makeWebhookContext({ body: 'plain text' });

			const result = await node.webhook.call(ctx);

			expect(result.workflowData).toEqual([[{ json: { body: 'plain text' } }]]);
		});

		it('answers an address outside the allowlist without reading the callback', async () => {
			const { ctx, response } = makeWebhookContext({
				options: { ipWhitelist: '198.51.100.0/24' },
				ip: '203.0.113.10',
				body: { id: 125 },
			});

			const result = await node.webhook.call(ctx);

			expect(result).toEqual({ noWebhookResponse: true });
			expect(response.writeHead).toHaveBeenCalledWith(403, expect.anything());
		});

		it('serves an address inside the allowlist', async () => {
			const { ctx } = makeWebhookContext({
				options: { ipWhitelist: '203.0.113.0/24' },
				ip: '203.0.113.10',
				body: { id: 125 },
			});

			const result = await node.webhook.call(ctx);

			expect(result.workflowData).toEqual([[{ json: { id: 125 } }]]);
		});

		it('answers a known crawler when the option is on', async () => {
			const { ctx, response } = makeWebhookContext({
				options: { ignoreBots: true },
				userAgent: 'Googlebot/2.1 (+http://www.google.com/bot.html)',
			});

			const result = await node.webhook.call(ctx);

			expect(result).toEqual({ noWebhookResponse: true });
			expect(response.writeHead).toHaveBeenCalledWith(403, expect.anything());
		});

		it('serves a known crawler while the option is off', async () => {
			const { ctx } = makeWebhookContext({
				userAgent: 'Googlebot/2.1 (+http://www.google.com/bot.html)',
				body: { id: 125 },
			});

			const result = await node.webhook.call(ctx);

			expect(result.workflowData).toEqual([[{ json: { id: 125 } }]]);
		});

		describe('Only Run If', () => {
			it('resolves nothing when the expression rejects the callback', async () => {
				const { ctx } = makeWebhookContext({
					options: { onlyRunIf: '={{ $json.body.status === "done" }}' },
					body: { status: 'processing' },
					evaluateExpression: vi.fn().mockReturnValue(false),
				});

				const result = await node.webhook.call(ctx);

				// No `workflowData` is what tells the handler this callback resolves nothing.
				expect(result.workflowData).toBeUndefined();
			});

			it('serves the callback when the expression accepts it', async () => {
				const { ctx } = makeWebhookContext({
					options: { onlyRunIf: '={{ $json.body.status === "done" }}' },
					body: { status: 'done' },
					evaluateExpression: vi.fn().mockReturnValue(true),
				});

				const result = await node.webhook.call(ctx);

				expect(result.workflowData).toEqual([[{ json: { status: 'done' } }]]);
			});

			it('lets the callback through when the expression fails to evaluate', async () => {
				const { ctx } = makeWebhookContext({
					options: { onlyRunIf: '={{ $json.body.missing.deep }}' },
					body: { status: 'done' },
					evaluateExpression: vi.fn().mockImplementation(() => {
						throw new Error('cannot read property of undefined');
					}),
				});

				const result = await node.webhook.call(ctx);

				expect(result.workflowData).toEqual([[{ json: { status: 'done' } }]]);
			});

			it('ignores a plain string, which is not an expression', async () => {
				const evaluateExpression = vi.fn();
				const { ctx } = makeWebhookContext({
					options: { onlyRunIf: 'status === "done"' },
					body: { status: 'processing' },
					evaluateExpression,
				});

				const result = await node.webhook.call(ctx);

				expect(evaluateExpression).not.toHaveBeenCalled();
				expect(result.workflowData).toEqual([[{ json: { status: 'processing' } }]]);
			});

			// The filter must not be reachable by a caller the gates already refused.
			it('is not evaluated for a request the address gate refused', async () => {
				const evaluateExpression = vi.fn();
				const { ctx } = makeWebhookContext({
					options: { ipWhitelist: '198.51.100.0/24', onlyRunIf: '={{ true }}' },
					ip: '203.0.113.10',
					evaluateExpression,
				});

				await node.webhook.call(ctx);

				expect(evaluateExpression).not.toHaveBeenCalled();
			});
		});

		describe('multipart callback', () => {
			it('keeps the fields and drops the files', async () => {
				const { ctx } = makeWebhookContext({
					contentType: 'multipart/form-data',
					body: {
						data: { id: '125', status: 'DONE' },
						files: { receipt: { filepath: '/tmp/does-not-exist-125' } },
					},
				});

				const result = await node.webhook.call(ctx);

				expect(result.workflowData).toEqual([[{ json: { id: '125', status: 'DONE' } }]]);
			});

			it('removes the files the callback uploaded, one or many per field', async () => {
				const dir = await mkdtemp(join(tmpdir(), 'callback-'));
				const paths = ['receipt.pdf', 'scan-1.png', 'scan-2.png'].map((name) => join(dir, name));
				await Promise.all(paths.map(async (path) => await writeFile(path, 'bytes')));

				try {
					const { ctx } = makeWebhookContext({
						contentType: 'multipart/form-data',
						body: {
							data: { id: '125' },
							files: {
								receipt: { filepath: paths[0] },
								scans: [{ filepath: paths[1] }, { filepath: paths[2] }],
							},
						},
					});

					await node.webhook.call(ctx);

					// Nothing else on this path removes them, and the endpoint can be called as often
					// as an external system likes.
					for (const path of paths) await expect(access(path)).rejects.toThrow();
				} finally {
					await rm(dir, { recursive: true, force: true });
				}
			});

			it('yields an object when a multipart callback carries no fields', async () => {
				const { ctx } = makeWebhookContext({
					contentType: 'multipart/form-data',
					body: { data: {}, files: {} },
				});

				const result = await node.webhook.call(ctx);

				expect(result.workflowData).toEqual([[{ json: {} }]]);
			});
		});

		describe('credentials', () => {
			it('refuses a callback the credential check rejects, without reading it', async () => {
				vi.mocked(validateWebhookAuthentication).mockRejectedValueOnce(
					new WebhookAuthorizationError(401),
				);
				const { ctx, response, getBodyData } = makeWebhookContext({ body: { id: 125 } });

				const result = await node.webhook.call(ctx);

				expect(result).toEqual({ noWebhookResponse: true });
				expect(response.writeHead).toHaveBeenCalledWith(
					401,
					expect.objectContaining({ 'WWW-Authenticate': expect.any(String) }),
				);
				expect(getBodyData).not.toHaveBeenCalled();
			});

			it('passes the status the check chose through to the caller', async () => {
				vi.mocked(validateWebhookAuthentication).mockRejectedValueOnce(
					new WebhookAuthorizationError(500, 'No authentication data defined on node!'),
				);
				const { ctx, response } = makeWebhookContext();

				expect(await node.webhook.call(ctx)).toEqual({ noWebhookResponse: true });
				expect(response.writeHead).toHaveBeenCalledWith(500, expect.anything());
			});

			it('lets any other failure of the check surface instead of answering for it', async () => {
				vi.mocked(validateWebhookAuthentication).mockRejectedValueOnce(
					new Error('credential store unavailable'),
				);
				const { ctx, response } = makeWebhookContext();

				await expect(node.webhook.call(ctx)).rejects.toThrow('credential store unavailable');
				expect(response.writeHead).not.toHaveBeenCalled();
			});
		});

		// A caller must learn that it was refused, never which check refused it: every refusal
		// is written the same way, with the same header, whatever check produced it.
		it('answers both gates and a credentials failure in the same shape', async () => {
			const refusals = [
				makeWebhookContext({ options: { ipWhitelist: '198.51.100.0/24' }, ip: '203.0.113.10' }),
				makeWebhookContext({
					options: { ignoreBots: true },
					userAgent: 'Googlebot/2.1 (+http://www.google.com/bot.html)',
				}),
				makeWebhookContext(),
			];
			vi.mocked(validateWebhookAuthentication).mockRejectedValueOnce(
				new WebhookAuthorizationError(401),
			);

			for (const { ctx } of refusals) {
				expect(await node.webhook.call(ctx)).toEqual({ noWebhookResponse: true });
			}

			const headersSent = refusals.map(({ response }) => response.writeHead.mock.calls[0][1]);
			expect(new Set(headersSent.map((h) => JSON.stringify(h))).size).toBe(1);
			for (const { response } of refusals) expect(response.end).toHaveBeenCalledTimes(1);
		});
	});
});
