import type {
	CallbackWaitRegistration,
	FromAIArgument,
	IExecuteFunctions,
	INode,
	IWebhookFunctions,
} from 'n8n-workflow';
import { NodeOperationError, traverseNodeParameters, WAIT_INDEFINITELY } from 'n8n-workflow';
import { mock } from 'vitest-mock-extended';

import { ToolWaitForCallback } from '../ToolWaitForCallback.node';

const NODE = mock<INode>({
	id: 'node-1',
	name: 'Wait for Callback',
	type: '@n8n/n8n-nodes-langchain.toolWaitForCallback',
	typeVersion: 1,
	webhookId: 'endpoint-a',
	parameters: {},
});

function makeExecuteContext({
	waitIdentifier = '125',
	toolCallId = 'call-1',
	registerCallbackWait = vi.fn(),
}: {
	waitIdentifier?: unknown;
	toolCallId?: string;
	registerCallbackWait?: ReturnType<typeof vi.fn>;
} = {}) {
	return mock<IExecuteFunctions>({
		getNode: () => NODE,
		getExecutionId: () => 'exec-1',
		getWorkflow: () => ({ id: 'wf-1' }) as never,
		getInputData: () => [{ json: { toolCallId, query: 'anything' } }],
		getNodeParameter: ((name: string) =>
			name === 'waitIdentifier' ? waitIdentifier : undefined) as never,
		putExecutionToWait: vi.fn(),
		helpers: { registerCallbackWait } as never,
	});
}

describe('ToolWaitForCallback', () => {
	const node = new ToolWaitForCallback();

	// The tool schema the LLM sees is generated by scanning node parameters for `$fromAI`
	// calls, so "only model-defined parameters are published" is a property of the
	// parameters themselves rather than of any code in this node.
	describe('tool schema', () => {
		const publishedKeys = (parameters: INode['parameters']) => {
			const collected: FromAIArgument[] = [];
			traverseNodeParameters(parameters, collected);
			return collected.map((argument) => argument.key);
		};

		it('publishes the wait identifier when its source is the model', () => {
			expect(
				publishedKeys({
					toolDescription: 'wait for a job',
					waitIdentifier: "={{ $fromAI('waitIdentifier', 'The job id', 'string') }}",
					callbackIdentifierSource: 'body',
					callbackIdentifier: '={{ $json.body.id }}',
					callbackAuthentication: 'none',
				}),
			).toEqual(['waitIdentifier']);
		});

		it.each([
			['fixed', 'processo-principal'],
			['an expression', '={{ $json.id }}'],
		])('publishes nothing when the wait identifier is %s', (_source, waitIdentifier) => {
			expect(
				publishedKeys({
					waitIdentifier,
					callbackIdentifierSource: 'body',
					callbackIdentifier: '={{ $json.body.id }}',
				}),
			).toEqual([]);
		});

		it("never publishes the callback identifier, which is the tool's own configuration", () => {
			expect(
				publishedKeys({
					waitIdentifier: "={{ $fromAI('waitIdentifier', 'The job id', 'string') }}",
					callbackIdentifier: '={{ $json.headers["x-request-id"] }}',
				}),
			).not.toContain('callbackIdentifier');
		});
	});

	describe('execute', () => {
		it('parks the execution when the wait is registered', async () => {
			const registerCallbackWait = vi.fn().mockResolvedValue({ status: 'registered' });
			const ctx = makeExecuteContext({ registerCallbackWait });

			await node.execute.call(ctx);

			expect(registerCallbackWait).toHaveBeenCalledWith({
				namespace: 'endpoint-a',
				correlationValue: '125',
				executionId: 'exec-1',
				toolCallId: 'call-1',
				nodeId: 'node-1',
				workflowId: 'wf-1',
			} satisfies CallbackWaitRegistration);
			expect(ctx.putExecutionToWait).toHaveBeenCalledWith(WAIT_INDEFINITELY);
		});

		it('returns the parked callback body without parking, when one already arrived', async () => {
			const ctx = makeExecuteContext({
				registerCallbackWait: vi
					.fn()
					.mockResolvedValue({ status: 'resolved', payload: { id: 125, status: 'DONE' } }),
			});

			const result = await node.execute.call(ctx);

			expect(result).toEqual([[{ json: { id: 125, status: 'DONE' } }]]);
			expect(ctx.putExecutionToWait).not.toHaveBeenCalled();
		});

		it('normalises a numeric identifier to its string form', async () => {
			const registerCallbackWait = vi.fn().mockResolvedValue({ status: 'registered' });

			await node.execute.call(makeExecuteContext({ waitIdentifier: 125, registerCallbackWait }));

			expect(registerCallbackWait).toHaveBeenCalledWith(
				expect.objectContaining({ correlationValue: '125' }),
			);
		});

		it.each([
			['an empty string', ''],
			['whitespace only', '   '],
			['null', null],
			['an object', { nested: true }],
			['a value beyond the stored length', 'x'.repeat(256)],
		])('refuses an identifier that cannot be correlated: %s', async (_case, waitIdentifier) => {
			const registerCallbackWait = vi.fn();

			await expect(
				node.execute.call(makeExecuteContext({ waitIdentifier, registerCallbackWait })),
			).rejects.toThrow(NodeOperationError);
			expect(registerCallbackWait).not.toHaveBeenCalled();
		});

		it('surfaces a refused registration to the agent', async () => {
			const ctx = makeExecuteContext({
				registerCallbackWait: vi.fn().mockRejectedValue(new Error('already active')),
			});

			await expect(node.execute.call(ctx)).rejects.toThrow('already active');
			expect(ctx.putExecutionToWait).not.toHaveBeenCalled();
		});

		it('refuses to park when the runtime grants no way to register a wait', async () => {
			// This is also what an agent that calls its tools in-process looks like: the
			// helper is only granted on the engine's node-execution path.
			const ctx = mock<IExecuteFunctions>({ getNode: () => NODE, helpers: {} as never });

			await expect(node.execute.call(ctx)).rejects.toThrow(NodeOperationError);
		});
	});

	describe('webhook', () => {
		it('returns the callback body and nothing else', async () => {
			const ctx = mock<IWebhookFunctions>({
				getNode: () => NODE,
				getNodeParameter: (() => 'none') as never,
				getBodyData: () => ({ id: 125, status: 'DONE' }),
				getHeaderData: () => ({ authorization: 'secret' }),
				getQueryData: () => ({ trace: 'abc' }),
			});

			const result = await node.webhook.call(ctx);

			expect(result.workflowData).toEqual([[{ json: { id: 125, status: 'DONE' } }]]);
		});

		it('wraps a non-object body so the tool result stays an object', async () => {
			const ctx = mock<IWebhookFunctions>({
				getNode: () => NODE,
				getNodeParameter: (() => 'none') as never,
				getBodyData: () => 'plain text' as never,
			});

			const result = await node.webhook.call(ctx);

			expect(result.workflowData).toEqual([[{ json: { body: 'plain text' } }]]);
		});
	});
});
